version: '3.8'

services:
  db:
    image: mysql
    restart: always
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - ./db-data:/var/lib/mysql